// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class InitializeRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):InitializeRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsInitializeRequest(bb:flatbuffers.ByteBuffer, obj?:InitializeRequest):InitializeRequest {
  return (obj || new InitializeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsInitializeRequest(bb:flatbuffers.ByteBuffer, obj?:InitializeRequest):InitializeRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new InitializeRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

logLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mutate_log_level(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeInt32(this.bb_pos + offset, value);
  return true;
}

static startInitializeRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLogLevel(builder:flatbuffers.Builder, logLevel:number) {
  builder.addFieldInt32(0, logLevel, 0);
}

static endInitializeRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createInitializeRequest(builder:flatbuffers.Builder, logLevel:number):flatbuffers.Offset {
  InitializeRequest.startInitializeRequest(builder);
  InitializeRequest.addLogLevel(builder, logLevel);
  return InitializeRequest.endInitializeRequest(builder);
}
}
