// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InitializeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsInitializeRequest(buf []byte, offset flatbuffers.UOffsetT) *InitializeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InitializeRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsInitializeRequest(buf []byte, offset flatbuffers.UOffsetT) *InitializeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InitializeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *InitializeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InitializeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InitializeRequest) LogLevel() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InitializeRequest) MutateLogLevel(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func InitializeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func InitializeRequestAddLogLevel(builder *flatbuffers.Builder, logLevel int32) {
	builder.PrependInt32Slot(0, logLevel, 0)
}
func InitializeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
