// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package model

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TeamRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTeamRequest(buf []byte, offset flatbuffers.UOffsetT) *TeamRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TeamRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTeamRequest(buf []byte, offset flatbuffers.UOffsetT) *TeamRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TeamRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TeamRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TeamRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TeamRequest) Team() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TeamRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TeamRequestAddTeam(builder *flatbuffers.Builder, team flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(team), 0)
}
func TeamRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
